import { IApartment } from '../shared/interfaces/apartment';

export const apartments: IApartment[] = [
  {
    _id: '644bca2010b6f9154a8d4db9',
    index: 6,
    isPremium: false,
    price: '$3,456.97',
    picture: 'http://placehold.it/32x32',
    icon: '🏡 ',
    type: 'Flat',
    title: 'et',
    rooms: {
      bedrooms: 3,
      bathrooms: 3,
    },
    agent: {
      name: 'Maritza Spence',
      email: 'maritzaspence@assurity.com',
      phone: '+1 (887) 510-2756',
    },
    address: '994 Duffield Street, Rivers, Michigan, 283',
    description: 'dolore nulla commodo voluptate ut et dolore',
    built: '2022-01-18T05:53:17 -03:00',
    tags: ['sint', 'magna', 'reprehenderit', 'quis', 'ad', 'minim', 'ipsum'],
  },
  {
    _id: '644bca20e5f76c3860c235da',
    index: 7,
    isPremium: true,
    price: '$3,937.14',
    picture: 'http://placehold.it/32x32',
    icon: '🛖 ',
    type: 'Detached House',
    title: 'nulla',
    rooms: {
      bedrooms: 5,
      bathrooms: 1,
    },
    agent: {
      name: 'Julie Hampton',
      email: 'juliehampton@assurity.com',
      phone: '+1 (851) 539-3576',
    },
    address: '640 Butler Place, Weedville, Wisconsin, 2116',
    description: 'velit anim excepteur culpa eiusmod magna mollit',
    built: '2016-10-27T06:53:06 -03:00',
    tags: ['culpa', 'voluptate', 'officia', 'minim', 'qui', 'ullamco', 'cillum'],
  },
  {
    _id: '644bca2077bef93b2909144f',
    index: 8,
    isPremium: false,
    price: '$3,846.44',
    picture: 'http://placehold.it/32x32',
    icon: '🏘️ ',
    type: 'House',
    title: 'labore',
    rooms: {
      bedrooms: 3,
      bathrooms: 3,
    },
    agent: {
      name: 'Joanne Crane',
      email: 'joannecrane@assurity.com',
      phone: '+1 (851) 418-3130',
    },
    address: '860 Woodhull Street, Cucumber, Illinois, 7397',
    description: 'cillum consectetur laboris mollit laboris nulla laborum',
    built: '2019-03-31T03:28:27 -03:00',
    tags: ['aliquip', 'tempor', 'proident', 'laborum', 'officia', 'ut', 'in'],
  },
  {
    _id: '644bca2077fb20b5f7193278',
    index: 9,
    isPremium: false,
    price: '$2,431.42',
    picture: 'http://placehold.it/32x32',
    icon: '🛕',
    type: 'Detached House',
    title: 'anim',
    rooms: {
      bedrooms: 5,
      bathrooms: 1,
    },
    agent: {
      name: 'Duncan Chang',
      email: 'duncanchang@assurity.com',
      phone: '+1 (941) 529-3583',
    },
    address: '270 Mill Road, Westmoreland, Delaware, 8376',
    description: 'consectetur officia irure minim tempor consectetur et',
    built: '2023-02-25T06:34:39 -03:00',
    tags: ['incididunt', 'enim', 'adipisicing', 'commodo', 'duis', 'duis', 'proident'],
  },
  {
    _id: '644bca209514c8e9f49dea14',
    index: 10,
    isPremium: false,
    price: '$1,791.68',
    picture: 'http://placehold.it/32x32',
    icon: '🏚️',
    type: 'Detached House',
    title: 'quis non do',
    rooms: {
      bedrooms: 5,
      bathrooms: 3,
    },
    agent: {
      name: 'Baird Goodwin',
      email: 'bairdgoodwin@assurity.com',
      phone: '+1 (885) 429-2213',
    },
    address: '201 Underhill Avenue, Noblestown, Texas, 8445',
    description: 'est exercitation cupidatat amet et mollit anim',
    built: '2016-06-23T02:30:28 -03:00',
    tags: ['excepteur', 'quis', 'dolor', 'sit', 'anim', 'commodo', 'dolor'],
  },

  {
    _id: '644bca208af6325c50de063a',
    index: 13,
    isPremium: true,
    price: '$1,666.40',
    picture: 'http://placehold.it/32x32',
    icon: '🏠',
    type: 'House',
    title: 'ex duis ipsum',
    rooms: {
      bedrooms: 3,
      bathrooms: 1,
    },
    agent: {
      name: 'Buckley Wall',
      email: 'buckleywall@assurity.com',
      phone: '+1 (927) 404-3878',
    },
    address: '454 Aitken Place, Greenock, Missouri, 521',
    description: 'eu esse anim proident aute irure occaecat',
    built: '2014-01-09T11:49:54 -03:00',
    tags: ['cupidatat', 'cupidatat', 'excepteur', 'Lorem', 'irure', 'culpa', 'commodo'],
  },
  {
    _id: '644bca20b4cbb3f546066019',
    index: 19,
    isPremium: false,
    price: '$3,791.07',
    picture: 'http://placehold.it/32x32',
    icon: '⛺',
    type: 'Flat',
    title: 'sint duis eu',
    rooms: {
      bedrooms: 5,
      bathrooms: 3,
    },
    agent: {
      name: 'Isabella Talley',
      email: 'isabellatalley@assurity.com',
      phone: '+1 (896) 408-3558',
    },
    address: '900 Luquer Street, Chapin, South Dakota, 2367',
    description: 'adipisicing deserunt cillum labore reprehenderit incididunt fugiat',
    built: '2020-03-14T02:15:59 -03:00',
    tags: ['et', 'do', 'do', 'est', 'quis', 'nostrud', 'voluptate'],
  },
];
